# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/web/main.go"
  bin = "./tmp/main"
  full_bin = "APP_PORT=8000 ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = []
  exclude_file = []
  log = "build-errors.log"
  delay = 1000 # ms
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500 # ms

[log]
  time = false

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
