name: CI/CD Staging

on:
  push:
    branches: ["staging"]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          # Menggunakan ID commit Git (SHA) sebagai tag untuk versioning yang unik dan andal.
          tags: ${{ secrets.DOCKER_USERNAME }}/golang-clean-architecture:${{ github.sha }}
          labels: "org.opencontainers.image.revision=${{ github.sha }}"

  deployment:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Test Network Connectivity
        run: |
          echo "Attempting to connect to host ${{ secrets.SERVER }} on port ${{ secrets.SERVER_PORT }}"
          nc -zv ${{ secrets.SERVER }} ${{ secrets.SERVER_PORT }}
      - name: Deploy to staging environment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            whoami
            cd /home/anno/golang-clean-architecture
            git pull origin staging

            export IMAGE_TAG=${{ github.sha }}

            # Stop and remove all running containers for this project
            docker compose -f docker-compose.prod.yml down

            # Forcibly remove the old, cached traefik image. Continue even if it fails (e.g., image not found).
            docker rmi traefik:v3.0 || true

            # Pull fresh images for all services
            docker compose -f docker-compose.prod.yml pull

            # Start all services fresh
            docker compose -f docker-compose.prod.yml up -d
          debug: true
